# Generated by Django 4.2.14 on 2024-07-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('name', models.TextField(max_length=2000)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=6700000900090909090)),
            ],
        ),
    ]
