# Generated by Django 4.2.14 on 2024-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_message_alter_message_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('project_name', models.TextField(primary_key=True, serialize=False)),
                ('project_description', models.TextField()),
            ],
        ),
    ]
